### ISSUE TITLE
"roslaunch px4 sfm.launch" cannot connect mavros

### ISSUE THREAD

**Issue by lulu402** [generalized-intelligence/GAAS#20]
when the command `roslaunch px4 sfm.launch` was finished ,I inputed `rostopic echo /mavros/state`

```
lulu@lulu-Vostro-3668:~$ rostopic echo /mavros/state
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
connected: False
armed: False
guided: False
mode: ''
system_status: 0
---
```
